#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run this script invoking that shell by setting the SHELL
#       environment variable to point to it before running, e.g.:
#           SHELL=/usr/bin/ksh ./gradlew
#
#   (2) The script will attempt to find a minimum viable Java installation
#       (which is either the newest Java version in "java.home" or in
#       $JAVA_HOME) in the order defined by the 'get_java_home' function.
#       If you explicitly set $JAVA_HOME, the script will use it as is.
#       If you explicitly set the 'java.home' property in gradle.properties,
#       the script will use the appropriate directory.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available file descriptors if possible.
# For more details, see https://docs.oracle.com/javase/8/docs/technotes/guides/vm/performance.html
if [ -n "$CENTRAL" ]; then
    ulimit -n 65536
fi

# Use the maximum available file descriptors if possible.
if [ -n "$MAX_FD" ]; then
    ulimit -n $MAX_FD
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * the classpath
#   * the default JVM options
#   * the java system properties
#   * the GRADLE_OPTS environment variable (if configured)
#   * the JAVA_OPTS environment variable (if configured)

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$(uname)" = "CYGWIN" ] || [ "$(expr substr $(uname -s) 1 5)" = "MINGW" ] || [ "$(expr substr $(uname -s) 1 6)" = "MSYS" ] ; then
    JAVA_HOME=$(cygpath --mixed "$JAVA_HOME")
    APP_HOME=$(cygpath --mixed "$APP_HOME")
fi

# Find the actual Java installation.
#
# If the 'JAVA_HOME' environment variable is set and points to a directory
# that exists, then we use that.
#
# In order of preference:
#  - The 'java.home' property in gradle.properties
#  - The 'JAVA_HOME' environment variable
#  - The 'java' executable in the PATH
#  - The 'which' command
#
get_java_home() {
    if [ -n "$JAVA_HOME" ] && [ -d "$JAVA_HOME" ]; then
        echo "$JAVA_HOME"
        return 0
    fi

    if [ -n "$JAVA_HOME" ]; then
        if [ -x "$JAVA_HOME/bin/java" ]; then
            echo "$JAVA_HOME"
            return 0
        fi
    fi

    if [ -x "$(command -v java)" ]; then
        java_cmd=$(command -v java)
        java_path=$(dirname "$(readlink -f "$java_cmd")")
        if [ -x "$java_path/javac" ]; then
            echo "$java_path"
            return 0
        fi
    fi

    echo ""
}

JAVA_HOME=$(get_java_home)

if [ -z "$JAVA_HOME" ] ; then
    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
    echo ""
    echo "Please set the JAVA_HOME variable in your environment to match the"
    echo "location of your Java installation."
    exit 1
fi

# Increase the maximum file descriptors if we can.
if [ -n "$CENTRAL" ]; then
    ulimit -n 65536
fi

# Collect the arguments.
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
        echo ""
        echo "Please set the JAVA_HOME variable in your environment to match the"
        echo "location of your Java installation."
        exit 1
    fi
else
    JAVACMD="java"
    if ! command -v java >/dev/null 2>&1; then
        echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
        echo ""
        echo "Please set the JAVA_HOME variable in your environment to match the"
        echo "location of your Java installation."
        exit 1
    fi
fi

# Collect the arguments.
GRADLE_OPTS="$GRADLE_OPTS -Dorg.gradle.appname=$APP_BASE_NAME"

# Add default JVM options
if [ -n "$DEFAULT_JVM_OPTS" ]; then
    GRADLE_OPTS="$DEFAULT_JVM_OPTS $GRADLE_OPTS"
fi

# Add the classpath
CLASSPATH="$CLASSPATH"

# Execute gradle
exec "$JAVACMD" $JAVA_OPTS $GRADLE_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
